# Site settings
title: Björn Johansson
email: bbjornjohansson@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "I'm Björn, a games programmer & designer from the middle of Sweden. Currently working on my bachelor's in GameDesign & #Programming at Uppsala University. On top of my relevant fields I'm a huge fan of freeride/powder skiing, skateboarding and all things games & ttrpg!"
keywords: "your keywords, separated by commas"
skills: "Programming - Game Design - IT"
meta_author: Johansson Björn

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 81ABBC #80B3FF 
  primary-rgb: "129, 171, 188" #"128,179,255"
  secondary: e6b451 #FD6E8A
  secondary-dark: 91A5A1 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Mastodon
    url: https://peoplemaking.games/@Bjorn
  - title: Linked-In
    url: https://www.linkedin.com/in/bj%C3%B6rn-johansson-84470b1ba/
  - title: Email
    url: mailto:bbjornjohansson@gmail.com
  - title: Itch.io
    url: https://outplayd.itch.io/
  - title: GitHub
    url: http://github.com/bjorn-johansson

# Postal address (add as many lines as necessary)
address:
  - line: Byrumsgatan 23
  - line: Visby, Gotland, Sweden

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
