# Site settings
title: Björn Johansson
email: bbjornjohansson@gmail.com
url: https://bjorndev.com
description: "I'm Björn, a games programmer & designer from the middle of Sweden. Currently working on my bachelor's in GameDesign & #Programming at Uppsala University. On top of my relevant fields I'm a huge fan of freeride/powder skiing, skateboarding and all things games & ttrpg!"
keywords: "Programming, Game Design, IT"
skills: "Programming - Game Design - IT"
meta_author: Johansson Björn

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 81ABBC #80B3FF 
  primary-rgb: "129, 171, 188" #"128,179,255"
  secondary: e6b451 #FD6E8A
  secondary-dark: e6b451 #A2122F

# Footer settings
footer:
  #copyright: Björn Johansson 2022
  location: Byrumsgatan 23
  social: 
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: fa-brands fa-mastodon
    url: https://peoplemaking.games/@Bjorn
  - title: fa-brands fa-linkedin
    url: https://www.linkedin.com/in/bj%C3%B6rn-johansson-84470b1ba/
  - title: fa-solid fa-envelope
    url: mailto:bbjornjohansson@gmail.com
  - title: fa-brands fa-itch-io
    url: https://outplayd.itch.io/
  - title: fa-brands fa-github
    url: http://github.com/bjorn-johansson

# Postal address (add as many lines as necessary)
address:
  - line: Byrumsgatan 23
  - line: Visby, Gotland, Sweden

# Credits content 
credits: 'testing to see if this is actually changing it'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
